### ISSUE TITLE
Items with multiple enchantments only have one when given to the player

### ISSUE THREAD

**Issue by Music4lity** [ZombieStriker/WishingWells_Bukkit#2]
Plugin version: 1.0.9
Server Version: PaperSpigot 1.8.8
Config: https://pastebin.com/TZaxssxp

Issue: When players receive the reward "sword", it has the name given, but only gives the unbreaking enchantment.
![image](https://user-images.githubusercontent.com/25295633/119929314-e1aead00-bf42-11eb-883c-d02a9367ad08.png)

**Comment by Music4lity** [comment]
Log output:
28.05 04:47:34 [Server] INFO [WishingWells] Enabling WishingWells v1.0.9
28.05 04:47:34 [Server] WARN java.lang.NullPointerException
28.05 04:47:34 [Server] WARN at me.zombie_striker.wishingwells.Main.itemStackParser(Main.java:280)
28.05 04:47:34 [Server] WARN at me.zombie_striker.wishingwells.Main.onEnable(Main.java:89)
28.05 04:47:34 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
28.05 04:47:34 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
28.05 04:47:34 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
28.05 04:47:34 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
28.05 04:47:34 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
28.05 04:47:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
28.05 04:47:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
28.05 04:47:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
28.05 04:47:34 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
28.05 04:47:34 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
